### ISSUE TITLE
Deploy Error

### ISSUE THREAD

**Issue by cyPABLO123456cy** [blenderskool/blaze#144]
### When i deploy this repository in my server . the follwing edrroe has occurred.
`
Build  [                    ] 0% (0.0s) compiling✖ ERROR TypeError: Cannot read properties of undefined (reading 'get')
    at /usr/blaze/node_modules/webpack/lib/DefinePlugin.js:292:38
    at SyncHook.eval [as call] (eval at create (/usr/local/lib/node_modules/preact-cli/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:27:1)
    at SyncHook.lazyCompileHook (/usr/local/lib/node_modules/preact-cli/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/usr/local/lib/node_modules/preact-cli/node_modules/webpack/lib/Compiler.js:631:26)
    at /usr/local/lib/node_modules/preact-cli/node_modules/webpack/lib/Compiler.js:667:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/local/lib/node_modules/preact-cli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/usr/local/lib/node_modules/preact-cli/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/usr/local/lib/node_modules/preact-cli/node_modules/webpack/lib/Compiler.js:662:28)
    at /usr/local/lib/node_modules/preact-cli/node_modules/webpack/lib/Compiler.js:321:11
    at Compiler.readRecords (/usr/local/lib/node_modules/preact-cli/node_modules/webpack/lib/Compiler.js:529:11)
    at /usr/local/lib/node_modules/preact-cli/node_modules/webpack/lib/Compiler.js:318:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/local/lib/node_modules/preact-cli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/usr/local/lib/node_modules/preact-cli/node_modules/tapable/lib/Hook.js:154:20)
    at /usr/local/lib/node_modules/preact-cli/node_modules/webpack/lib/Compiler.js:315:19
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/local/lib/node_modules/preact-cli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/usr/local/lib/node_modules/preact-cli/node_modules/tapable/lib/Hook.js:154:20)
`

**Comment by blenderskool** [comment]
Can you add more details about how you deployed Blaze on your server?
Did you use the provided docker images?

**Comment by blenderskool** [comment]
Closing this issue as additional details were not provided.
